-- 创建导航表
CREATE TABLE IF NOT EXISTS nav (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    name VARCHAR(50) NOT NULL COMMENT '导航名称',
    path VARCHAR(100) NOT NULL COMMENT '导航路径',
    children_id BIGINT COMMENT '子导航ID'
) COMMENT '导航表';

-- 创建新闻表
CREATE TABLE IF NOT EXISTS news (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    title VARCHAR(100) NOT NULL COMMENT '新闻标题',
    `describe` TEXT COMMENT '新闻描述',
    text TEXT COMMENT '新闻内容',
    img_id BIGINT COMMENT '图片ID',
    author VARCHAR(50) COMMENT '作者',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT '新闻表';

-- 创建图片表
CREATE TABLE IF NOT EXISTS img (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    url VARCHAR(255) NOT NULL COMMENT '图片URL'
) COMMENT '图片表';

-- 创建产品表
CREATE TABLE IF NOT EXISTS products (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    name VARCHAR(100) NOT NULL COMMENT '产品名称',
    img_id BIGINT COMMENT '图片ID'
) COMMENT '产品表'; 